# Tensor Operationen

## Numpy basics

In [21]:
import numpy as np 

In [22]:
# a ist ein numpy array
a = np.ones((2,))
type(a)

numpy.ndarray

In [23]:
# im numpy array sind floats gespeichert
a.dtype

dtype('float64')

In [24]:
# andere Datentypen wie z.B. integers sind auch möglich
a = np.ones((2,), dtype=int)
a.dtype

dtype('int64')

In [25]:
#2D Tensor (Matrix)
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [26]:
#3D Tensor
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [27]:
#Einheitsmatrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#1D array
np.arange(100)

In [28]:
start = -5
stop = 20
step = 2
np.arange(start, stop, step)

array([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
# slicing: 
A = np.arange(0,100)
A[42:50]

array([42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
# multidimensionales slicing
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
A[2:3,0:3]

array([[0., 0., 1.]])

In [ ]:
# Mit ndim lässt sich der Rang des Tensors herausfinden
A = np.ones((2,3,5))
A.ndim

In [ ]:
# Mit shape lassen sich die Länge der Arrays in den einzelnen Dimensionen des Tensors herausfinden
A = np.ones((2,3,5))
A.shape

### Grundrechenarten

In [29]:
a = np.array([1,2,3,4]) # numpy array from list
a

array([1, 2, 3, 4])

In [30]:
b = 10 * a
b

array([10, 20, 30, 40])

In [31]:
b-a

array([ 9, 18, 27, 36])

In [32]:
a+b

array([11, 22, 33, 44])

In [33]:
#Punktweise Multiplikation
a*b

array([ 10,  40,  90, 160])

In [34]:
#Skalarprodukt
a@b

300

In [35]:
A = np.ones((3, 3))
np.exp(A) #Exponentialfunktion

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [36]:
# exponieren
A**6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
A.sum()

9.0

In [38]:
A = np.arange(15).reshape((3, 5))   # reshape schauen wir noch genauer an
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
A.max()

14

In [40]:
A.sum(axis=0) # sum of column

array([15, 18, 21, 24, 27])

In [41]:
A.sum(axis=1) # sum of row

array([10, 35, 60])

In [42]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

# Übung: 
    - Erstelle eine 5x5-Matrix mit 7ern auf der Diagonalen
    - Erstelle eine 7x7-Matrix mit Nullen am Rand und Einsen in der Mitte
   

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Tensoroperationen sind stark optimiert

In [2]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] = max(x[i, j], 0)
    return x

In [3]:
def naive_add(x, y):
    assert len(x.shape) == 2 
    assert x.shape == y.shape 
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] += y[i, j]
    return x

In [4]:


x = np.random.random((20, 100)) 
y = np.random.random((20, 100))



In [5]:
%timeit z = x + y

1.26 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
%timeit z = naive_add(x, y)

783 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
z = x + y
%timeit zz = np.maximum(z, 0.)

3.22 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%timeit zz = naive_relu(z)

990 µs ± 41.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Broadcasting Beispiel

In [9]:
# Die Grundrechenarten und die Anwendung von Funktionen sind elementwise definiert
x = np.random.random((64, 3, 32, 10)) 
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [10]:
z.shape

(64, 3, 32, 10)

# Dot Produkt

In [11]:
x = np.random.random((1,32)) 
y = np.random.random((32,1)) 
z = np.dot(x, y)

In [12]:
z

array([[8.3879487]])

In [13]:
# VORSICHT! MANCHE MENSCHEN MEINEN DOT-PRODUKT SOLLTE AUCH BEI MATRIZEN SKALAREN OUTPUT HABEN
x = np.random.random((32,5)) 
y = np.random.random((5,32)) 
z = np.dot(x, y)

In [14]:
z.shape

(32, 32)

In [15]:
x = np.random.random((9,3,4,8))
y = np.random.random((8,2)) # aber (8,2,3) geht nicht.

z = np.dot(x,y)
z.shape

(9, 3, 4, 2)

In [16]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1 
    assert len(y.shape) == 1 
    assert x.shape[0] == y.shape[0] 
    
    z = 0.
    for i in range(x.shape[0]): 
        z += x[i] * y[i]
    return z

In [17]:
def naive_matrix_vector_dot(x, y): 
    assert len(x.shape) == 2 
    assert len(y.shape) == 1 
    assert x.shape[1] == y.shape[0] 
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]): 
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

# Übung
* Benchmarken der beiden naiven Implementierungen vs Numpy
* Wie ändert sich die Runtime mit der Dimensionalität des Inputs?

823 ns ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


36.7 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Tensor Reshaping

In [17]:
x = np.array([[0., 1.], 
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [18]:
x = x.reshape((6, 1))

In [19]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [20]:
x = x.reshape((2,3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [21]:
x = x.reshape((3,2))
x

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [22]:
# Aber: transponieren ändert die Reihenfolge
x = x.transpose()
x

array([[0., 2., 4.],
       [1., 3., 5.]])

In [23]:
x = x.reshape((3,2))
x

array([[0., 2.],
       [4., 1.],
       [3., 5.]])