# Tensor Operationen

## Numpy basics

In [1]:
import numpy as np 

In [2]:
# a ist ein numpy array
a = np.ones((2,))
type(a)

numpy.ndarray

In [3]:
# im numpy array sind floats gespeichert
a.dtype

dtype('float64')

In [4]:
# andere Datentypen wie z.B. integers sind auch möglich
a = np.ones((2,), dtype=int)
a.dtype

dtype('int64')

In [5]:
a

array([1, 1])

In [6]:
#2D Tensor (Matrix)
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
#3D Tensor
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
#Einheitsmatrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#1D array
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
start = -5
stop = 20
step = 2
np.arange(start, stop, step)

array([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
# slicing: 
A = np.arange(0,100)
A[42:50]

array([42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
# multidimensionales slicing
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
A[1:3,0:3]

array([[0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Mit ndim lässt sich der Rang des Tensors herausfinden
A = np.ones((2,3,5))
A.ndim

3

In [16]:
# Mit shape lassen sich die Länge der Arrays in den einzelnen Dimensionen des Tensors herausfinden
A = np.ones((2,3,5))
A.shape

(2, 3, 5)

### Grundrechenarten

In [17]:
a = np.array([1,2,3,4]) # numpy array from list
a

array([1, 2, 3, 4])

In [18]:
b = 10 * a
b

array([10, 20, 30, 40])

In [19]:
b-a

array([ 9, 18, 27, 36])

In [20]:
a+b

array([11, 22, 33, 44])

In [21]:
#Punktweise Multiplikation
a*b

array([ 10,  40,  90, 160])

In [22]:
#Skalarprodukt
a@b

300

In [23]:
np.dot(a,b)

300

In [24]:
A = np.ones((3, 3))
np.exp(A) #Exponentialfunktion

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [26]:
# exponieren
A = np.ones((3, 3)) + np.ones((3, 3))
A**6

array([[64., 64., 64.],
       [64., 64., 64.],
       [64., 64., 64.]])

In [27]:
A.sum()

18.0

In [28]:
A = np.arange(15).reshape((3, 5))   # reshape schauen wir noch genauer an
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
A.max()

14

In [32]:
A.shape

(3, 5)

In [30]:
A.sum(axis=0) # sum of column

array([15, 18, 21, 24, 27])

In [31]:
A.sum(axis=1) # sum of row

array([10, 35, 60])

In [35]:
A[0,4] = 100
A

array([[100,   1,   2,   3, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [42]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

# Übung: 
    - Erstelle eine 5x5-Matrix mit 7ern auf der Diagonalen
    - Erstelle eine 7x7-Matrix mit Nullen am Rand und Einsen in der Mitte
   

In [36]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
A = A*7
A

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

In [68]:
B = np.zeros((7,7))
for i in range(7):
    for j in range(7):
        if min(i,j) and max(i,j)<6:
            B[i,j]=1
B

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Tensoroperationen sind stark optimiert

In [38]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] = max(x[i, j], 0)
    return x

In [39]:
def naive_add(x, y):
    assert len(x.shape) == 2 
    assert x.shape == y.shape 
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] += y[i, j]
    return x

In [40]:


x = np.random.random((20, 100)) 
y = np.random.random((20, 100))



In [42]:
type(x)

numpy.ndarray

In [43]:
%timeit z = x + y

1.21 µs ± 22.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [44]:
%timeit z = naive_add(x, y)

957 µs ± 37.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [45]:
z = x + y
%timeit zz = np.maximum(z, 0.)

3.67 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
%timeit zz = naive_relu(z)

1.1 ms ± 4.24 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Broadcasting Beispiel

In [47]:
# Die Grundrechenarten und die Anwendung von Funktionen sind elementwise definiert
x = np.random.random((64, 3, 32, 10)) 
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [48]:
z.shape

(64, 3, 32, 10)

# Dot Produkt

In [49]:
x = np.random.random((1,32)) 
y = np.random.random((32,1)) 
z = np.dot(x, y)

In [52]:
z

array([[8.80363405]])

In [53]:
z.shape

(1, 1)

In [54]:
z = np.dot(y, x)

In [55]:
z.shape   

(32, 32)

In [56]:
# VORSICHT! MANCHE MENSCHEN MEINEN DOT-PRODUKT SOLLTE AUCH BEI MATRIZEN SKALAREN OUTPUT HABEN
x = np.random.random((32,5)) 
y = np.random.random((5,32)) 
z = np.dot(x, y)

In [57]:
z.shape

(32, 32)

In [58]:
x = np.random.random((9,3,4,8))
y = np.random.random((8,2)) # aber (8,2,3) geht nicht.

z = np.dot(x,y)
z.shape

(9, 3, 4, 2)

In [59]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1 
    assert len(y.shape) == 1 
    assert x.shape[0] == y.shape[0] 
    
    z = 0.
    for i in range(x.shape[0]): 
        z += x[i] * y[i]
    return z

In [60]:
def naive_matrix_vector_dot(x, y): 
    assert len(x.shape) == 2 
    assert len(y.shape) == 1 
    assert x.shape[1] == y.shape[0] 
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]): 
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

13.3 µs ± 699 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Übung
* Benchmarken der beiden naiven Implementierungen vs Numpy
* Wie ändert sich die Runtime mit der Dimensionalität des Inputs?

In [18]:
x = np.random.random((100))
y = np.random.random((100))

In [19]:
%timeit np.dot(x,y)

823 ns ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
%timeit naive_vector_dot(x, y)

36.7 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Tensor Reshaping

In [66]:
x = np.array([[0., 1.], 
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [67]:
x = x.reshape((6, 1))

In [68]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [69]:
x = x.reshape((2,3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [70]:
x = x.reshape((3,2))
x

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [71]:
# Aber: transponieren ändert die Reihenfolge
x = x.transpose()
x

array([[0., 2., 4.],
       [1., 3., 5.]])

In [72]:
x = x.reshape((3,2))
x

array([[0., 2.],
       [4., 1.],
       [3., 5.]])